services:
  - type: web
    name: go-bookstore-api
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: DATABASE_URL
        fromService:
          type: pserv
          name: neon-database